<div id="footer" class="box informational">
    <ul>
        <li>
            <h4>МЫ В СОЦИАЛЬНЫХ СЕТЯХ</h4>
                <p class="social-networks">
                    <a href="https://www.facebook.com/MiroslavaIrina" target="_blank"><img src="{{media url="wysiwyg/networks_fc_new.png"}}" alt="facebook"  /></a>
                    <a href="https://www.instagram.com/miranova_irina/?utm_source=ig_profile_share&igshid=dwtnpyxdhpj7" target="_blank"><img src="{{media url="wysiwyg/networks_inst_new.png"}}" alt="instagram" /></a>
                    <a href="https://vk.com/termostrazu." target="_blank"><img src="{{media url="wysiwyg/networks_vk_new1.png"}}" alt="Vk" /></a>
                </p>
        </li>
        <li>
            <h4>СВЯЗАТЬСЯ С НАМИ</h4>
                <ul class="footer-link">
                    <li><span><img src="{{media url="wysiwyg/networks_viber_1.jpg"}}" alt="viber" />0500323183</span></li>
                    <li><span><img src="{{media url="wysiwyg/networks_skype_1.jpg"}}" alt="skype" />sav.s.2011</span></li>
                    <li><span><img src="{{media url="wysiwyg/networks_tel.jpg"}}" alt="telephone number" />0500323183</span></li>
                </ul>
        </li>
        <li>
            <h4>СОВЕТЫ И ПОМОЩЬ</h4>
                <ul class="footer-link">
                    <li><a href="{{store direct_url='delivery'}}">Доставка и оплата</a></li>
                    <li><a href="{{store direct_url='returns}}">Возврат товаров</a></li>
                    <li><a href="{{store direct_url='tablesize'}}">Таблица размеров</a></li>
                </ul>
        </li>
    </ul>
</div>


<!--<div class="box informational">
    <ul>
        <li>
            <h4>О нас</h4>
            <ul style="width: 100%;">
                <li style="float: left; margin-left: 25px;"><a href="{{store direct_url='about'}}">О нас</a></li>
                <li style="float: left; margin-left: 25px;"><a href="{{store direct_url='contacts'}}">Наши контакты</a></li>
                <li style="float: left; margin-left: 25px;"><a href="{{store direct_url='delivery'}}">Информация о доставке</a></li>
                <li style="float: left; margin-left: 25px;"><a href="{{store direct_url='returns'}}">Политика возврата</a></li>
            </ul>
        </li>
      <li>
            <h4>Customer information</h4>
            <ul>
                <li><a href="{{store direct_url='contacts'}}">Contact Us</a></li>
                <li><a href="{{store direct_url='price-matching'}}">Price matching</a></li>
                <li><a href="{{store direct_url='testimonials'}}">Testimonials</a></li>
            </ul>
        </li>
        <li>
            <h4>Security &amp; privacy</h4>
            <ul>
                <li><a href="{{store direct_url='privacy'}}">Privacy Policy</a></li>
                <li><a href="{{store direct_url='safe-shopping'}}">Safe &amp; secure shopping</a></li>
                <li><a href="{{store direct_url='terms'}}">Terms &amp; conditions</a></li>
            </ul>
        </li>
        <li class="last">
            <h4>Shipping &amp; returns</h4>
            <ul>
                <li><a href="{{store direct_url='delivery'}}">Delivery information</a></li>
                <li><a href="{{store direct_url='guarantees'}}">Satisfaction guarantee</a></li>
                <li><a href="{{store direct_url='returns'}}">Returns policy</a></li>
            </ul>
        </li>
    </ul>
</div>-->

